spring.application.name=farm_Backend

spring.datasource.url=jdbc:mysql://localhost:3306/farm_backend?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=1234@Bhagesh
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# JWT Secret Key (Should be in environment variable in production)
application.security.jwt.secret-key=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970

# Cloudinary Configuration
cloudinary.cloud_name=dmgtwx94i
cloudinary.api_key=768418587429958
cloudinary.api_secret=_5qeT5JgZu-RoEmsIXtk4UcdMtc
